config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  
  resources :items do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
validates :name, presence: true, length: { maximum: 50 },
uniqueness: { case_sensitive: false }

validates :location, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.order(Item.arel_table['name'].lower.asc).paginate(page: params[:page]).per_page(20)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, notice: 'Item could not be created.' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
   @item.destroy
#__elasticsearch__.delete_item
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    query = params[:search_items].presence && params[:search_items][:query]

    if query
      @items = Item.fuzzy_search(query)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :location)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@item) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rubibase</h1>

<h1>Search Items</h1>

<p>
  Press <%= link_to 'here', search_items_path %> to search for items.
</p>

<h1>Add an Item</h1>
<p>
Press here to add a new item to the database: <%= link_to 'New Item', new_item_path %>
</p>

<% unless @items.blank? %>
<%= will_paginate %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
		<td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>
<% else %>
<p> There is no data in the database yet </p>
<% end %>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<div class="row">
	<div class="col-md-4">
		<%= form_for(@item) do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
		
		<%= f.label :location %>
		<%= f.text_field :location, class: 'form-control' %>
		
		<%= f.submit "Create item", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/items/search.html.erb
<h1>Search for items</h1>

<%= form_for :search_items, url: search_items_path, method: :get do |form| %>
  <%= form.text_field :query, value: params[:search_items].presence && params[:search_items][:query] %>
  <%= form.submit 'Search' %>
<% end %>

<% unless @items.nil? %>
  <% if @items.empty? %>
    <h2>No items found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>
	
	<table style="width: 100%;">
	      <thead>
	         <tr>
	           <th>Item name</th>
	           <th>Location</th>
			   <th>Actions</th>
	         </tr>
	      </thead>

	      <tbody>
	        <% @items.each do |item| %>
	          <tr>
	            <td><%= item.name %></td>
	            <td><%= item.location %></td>
	            <td><%= link_to 'View', item_path(item.id) %></td>
	          </tr>
	        <% end %>
	      <tbody>
	   </table>
	<% end %>
<% end %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Item </h1>
	<p> <%= @item.name %> </p>
<h1> Location </h1>
	<p> <%= @item.location %> </p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">

      <!-- Elements visible all the time -->
      <div class="col-sm-7">
        <%= render 'layouts/navigation/header' %>
      </div><!-- col-sm-7 -->

      <!-- Elements collapses on smaller devices -->
      <div class="col-sm-5">
        <%= render 'layouts/navigation/collapsible_elements' %>
      </div><!-- col-sm-5 -->

    </div><!-- row -->
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubibase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>